version: "3"
services:
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8001:8000
    volumes:
      - .:/app
    depends_on:
      - db
    restart: always
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5433:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always

volumes:
  postgres_data:
