version: "3"

services:
  nginx:
    build: ./nginx
    ports:
      - 8080:80
    depends_on:
      - web

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - static:/static
    env_file:
      - .env
    depends_on:
      - db
    restart: always

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5433:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always

volumes:
  static:
  postgres_data:
