version: '3'
services:
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - app2
  
  app2:
    build: 
      context: ../app_django_docker
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000 
    container_name: container-app2
    expose:
      - 8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
      image: postgres:13.0-alpine
      volumes:
         - postgres_data:/var/lib/postgresql/data/
      env_file:
         - ./.env.dev
      restart: always
      

volumes:
  postgres_data:
      